import IndustryExplorer from '../components/ai/IndustryExplorer';
import SavingsSimulator from '../components/ai/SavingsSimulator';
import AIApproach from '../components/ai/AIApproach';
import HeroExperience from '../components/HeroExperience';
import WorksShowcase from '../components/WorksShowcase';
import BlogCards from '../components/BlogCards';
import {pageMetadata,siteUrl} from '../lib/seo';
export const metadata=pageMetadata('');
import Services from '../components/Services';
import SwipeRail from '../components/SwipeRail';
import ContactBrief from '../components/ContactBrief';
import HomeDetails from '../components/HomeDetails';
const steps=[['相談する','実現したいこと、今の課題や予算をお聞かせください。'],['整理する','必要な機能と優先順位を整理し、費用をご提案します。'],['デザインする','実際の画面を見ながら、使いやすい体験を設計します。'],['つくる','大切な機能から開発し、動作を確認します。'],['育てる','公開後の声をもとに、改善や機能追加を支援します。']];
const faq=[['アイデアだけでも相談できますか？','はい。まだ内容が固まっていなくても大丈夫です。目的や利用者を整理し、必要な機能と進め方を一緒に考えます。'],['小規模な制作・改修にも対応していますか？','はい。LP制作、既存サイトの改善、小さな業務ツール、機能追加など、必要な範囲に絞って対応します。'],['アプリとWebシステム、どちらがよいですか？','利用場面、必要な機能、予算、運用方法を伺ってご提案します。Web版で検証してからアプリ化する進め方も可能です。'],['開発期間はどのくらいですか？','Webサイトは1〜4週間程度が目安です。アプリ・業務システムは機能により異なるため、ヒアリング後にスケジュールをご提示します。'],['公開後の保守や改善もお願いできますか？','はい。文章・画像の更新、障害対応、機能改善など、内容に合わせて継続的にサポートします。'],['相談したら契約しなければなりませんか？','いいえ。初回相談は無料です。ご提案とお見積もりをご確認いただいたうえで、ご依頼をご判断ください。']];
export default function Home(){return <main id="main-content"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'Organization','@id':siteUrl+'/#organization',name:'Aiplun Studio',url:siteUrl,email:'royryu221317@gmail.com',logo:siteUrl+'/aiplun-icon.png',description:'AIとシステムによる業務効率化・自動化を、業務整理から開発・運用改善まで支援。Web制作・アプリ開発にも対応する開発スタジオ。'},{'@type':'WebSite','@id':siteUrl+'/#website',url:siteUrl,name:'Aiplun Studio',inLanguage:'ja',publisher:{'@id':siteUrl+'/#organization'}},{'@type':'WebPage','@id':siteUrl+'/#webpage',url:siteUrl+'/',name:metadata.title,description:metadata.description,inLanguage:'ja',isPartOf:{'@id':siteUrl+'/#website'},about:{'@id':siteUrl+'/#organization'}},{'@type':'VideoObject','@id':siteUrl+'/#brand-film',name:'Aiplun Studio ブランドムービー — 仕事に、余白を。',description:'繰り返す仕事を仕組みに変え、人にしかできない仕事へ。AI・システム・Web・アプリ開発を紹介する30秒のブランドムービー。',thumbnailUrl:siteUrl+'/media/aiplun-brand-film-poster.webp',contentUrl:siteUrl+'/media/aiplun-brand-film-30s.mp4',uploadDate:'2026-10-04T00:00:00+09:00',duration:'PT30S',inLanguage:'ja',publisher:{'@id':siteUrl+'/#organization'}}]}).replace(/</g,'\\u003c')}}/><HeroExperience/>
<section className="decision-overview wrap" aria-labelledby="decision-title"><div className="decision-heading"><p className="eyebrow">ご依頼を検討中の方へ</p><h2 id="decision-title">実績・費用・進め方を、まず確認。</h2></div><div className="decision-grid"><a href="#works"><span className="decision-label">開発実績</span><h3>公開済みアプリと、LINE連携CRM。</h3><p>自社開発のアイプラ・クエストAIの実画面と、Web制作サンプルをご覧いただけます。</p><strong>実績・制作例を見る</strong></a><a href="#pricing"><span className="decision-label">費用</span><h3>ライト制作は3万円〜。</h3><p>Web・アプリ・業務システムは個別見積もり。範囲と費用を確認してから着手します。</p><strong>費用と制作範囲を見る</strong></a><a href="#strengths"><span className="decision-label">対応体制</span><h3>相談から公開後の改善まで。</h3><p>初回相談無料・全国オンライン対応。お問い合わせには原則48時間以内に返信します。</p><strong>進め方とサポートを見る</strong></a></div></section>
<section className="section wrap" id="services"><div className="section-top"><p className="eyebrow">01 — WHAT WE DO</p><span className="section-note">4つの領域を、ひとつのチームで。</span></div><div className="section-heading"><h2>AI・システム・Web・アプリ。<br/>事業を支える、4つの支援。</h2><p>日々の業務改善から、新しいサービスづくりまで。<br/>課題の整理から開発・運用まで、一緒に進めます。</p></div><Services/></section>
<section className="works-section" id="works"><div className="wrap"><div className="section-top"><p className="eyebrow">02 — WORKS & SHOWCASE</p><span className="section-note">自分たちでも、つくり、育てています。</span></div><WorksShowcase/><div className="examples"><p>こんな開発にも対応しています <small>※ 対応可能な開発例です。</small></p><SwipeRail id="examples-track" label="対応可能な開発例" className="examples-track"><a href="/services/business-systems"><span>01 / SYSTEM</span><h3>顧客・案件管理</h3><p>情報と対応履歴をまとめ、毎日の管理をスムーズに。</p><strong>対応範囲を見る →</strong></a><a href="/services/ai-automation"><span>02 / AI</span><h3>AIナレッジ検索</h3><p>社内の資料や情報から、必要な答えを探せる仕組み。</p><strong>対応範囲を見る →</strong></a><a href="/services/web-production"><span>03 / WEB</span><h3>サービス・企業サイト</h3><p>事業の強みを伝え、相談につながるホームページ。</p><strong>対応範囲を見る →</strong></a></SwipeRail></div></div></section>
<section className="section wrap budget" id="pricing"><div><p className="eyebrow">03 — BUDGET</p><h2>目的に合わせて、<br/>必要な開発を。</h2><p>Web制作・システム開発・MVP開発。<br/>実現したいことを整理し、範囲と費用をご提案します。</p><a className="text-link" href="/plans">費用・開発規模の目安 <span>↗</span></a></div><div className="budget-list"><a href="/plans#web"><div><h3>Web制作</h3><p>事業の魅力を伝え、問い合わせにつなげるサイト</p></div><strong className="quote">個別見積もり ↗</strong></a><a href="/plans#system"><div><h3>システム開発</h3><p>顧客管理・LINE連携・業務の自動化</p></div><strong className="quote">個別見積もり ↗</strong></a><a href="/plans#mvp"><div><h3>MVP開発</h3><p>新規サービスの検証に必要な機能を形に</p></div><strong className="quote">個別見積もり ↗</strong></a><p className="budget-note">内容・規模に合わせて、着手前にお見積もりします。</p><aside className="light-offer"><div><p className="eyebrow">SMALL START</p><h3>ライト制作 <span>3万円〜</span></h3><p>掲載内容と制作範囲を絞って、小さく公開したい方へ。対応範囲はご相談時に確認します。</p></div><a href="/plans#light">ライト制作の詳細 →</a></aside></div></section>
<section className="section wrap" id="strengths"><div className="section-top"><p className="eyebrow">04 — OUR APPROACH</p></div><div className="approach-layout"><div className="approach-intro"><h2>相談から公開後まで。<br/><span className="blue">進め方を共有します。</span></h2><p className="support-intro">必要な機能・予算・スケジュールを確認してから制作へ。公開後の更新や改善もご相談いただけます。</p></div><div className="approach-list">{[['必要な機能を、一緒に絞る。','誰が、どんな場面で使うのか。まず取り組む範囲を整理し、機能と費用を確認してから開発に進みます。'],['画面を見ながら、決める。','文章だけでは伝わりにくい操作や配置も、画面を共有して確認。使う人の動きに合わせて調整します。'],['公開後の更新も、相談できる。','文章や画像の更新、機能の追加、日々の運用で気づいた改善。必要な支援の範囲を相談しながら対応します。']].map(([title,text],i)=><article key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
<section className="process-section" id="flow"><div className="wrap"><div className="section-top"><p className="eyebrow">05 — HOW WE BUILD</p></div><div className="section-heading"><h2>最初の会話から、<br/>一歩ずつ。</h2><p>専門用語に詳しくなくても大丈夫。<br/>進捗と判断材料を共有しながら進めます。</p></div><SwipeRail id="process-track" label="開発の流れ" className="process-grid" as="ol">{steps.map(([title,text],i)=><li key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></li>)}</SwipeRail></div></section>
<section className="home-more wrap" aria-label="AI活用の詳しい情報"><HomeDetails id="ai-impact" title="業種別のAI導入イメージ" description="セミナー・介護・店舗・営業の業務改善例"><IndustryExplorer/><AIApproach/></HomeDetails><HomeDetails id="ai-simulator" title="業務時間・コストの削減額を試算" description="人数や作業時間を入力して確認できます"><SavingsSimulator/></HomeDetails></section>
<section className="team-section" id="team" aria-labelledby="team-title"><div className="wrap"><div className="team-heading"><p className="eyebrow">私たちについて</p><h2 id="team-title">誰かの「困った」を、<br/>自分たちで作って解決したい。</h2><p>立命館大学で学ぶ二人で、Aiplun Studioを運営しています。アイプラやクエストAIなど、自分たちのサービスを開発しながら、アプリ・Webサイト・業務システムの制作に取り組んでいます。</p></div><div className="team-members"><article className="team-member"><div className="member-heading"><span className="member-initial" aria-hidden="true">R</span><div><p className="member-role">Aiplun Studio 共同代表</p><h3>尾島 蓮瑛 <span>おじま ろい</span></h3><p className="member-school">立命館大学 法学部</p></div></div><p>誰かの夢や挑戦を聞き、現場を知り、自分に何ができるかを考えて形にする。その過程にやりがいを感じています。</p><p>お客様を一番に考え、実現したいことや困っていることを丁寧に伺うことを大切にしています。ご予算や日々の使い方にも目を向け、本当に必要なものを一緒に考えます。</p><p className="member-belief">お客様の想いを起点に、作ったものが役に立つところまで向き合いたい。</p></article><article className="team-member"><div className="member-heading"><span className="member-initial" aria-hidden="true">R</span><div><p className="member-role">Aiplun Studio</p><h3>共同代表</h3><p className="member-school">立命館大学 情報理工学部</p></div></div><p>尾島と同じ大学で学び、これまで活動を共にしてきたパートナーです。Aiplun Studioの共同代表として、サービスづくりに取り組んでいます。</p><p>それぞれ異なる分野を学ぶ二人で、アイデアを話し合い、実際に使える形へ。自社サービスの開発と改善を重ねながら、制作に向き合っています。</p></article></div><div className="team-footer"><p>「何を作ればよいか」から、一緒に考えます。</p><a className="text-link" href="#contact">私たちに相談する <span>→</span></a></div></div></section>
<section className="faq-section wrap section" id="faq"><div><p className="eyebrow">06 — FAQ</p><h2>気になることを、<br/>あらかじめ。</h2></div><div className="faq-list">{faq.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
<section className="section wrap blog-home" id="blog"><p className="eyebrow">FIELD NOTES</p><div className="blog-home-heading"><h2>仕事の中で、AIを使う。</h2><a className="text-link" href="/blog">ブログ一覧を見る ↗</a></div><p className="blog-home-lead">企業はAIをどう使っている？公式事例と、身近な業務で試せる活用方法。</p><BlogCards limit={3}/></section>
<section className="contact" id="contact"><div className="wrap"><p className="eyebrow">LET’S BUILD SOMETHING GOOD.</p><div className="contact-grid"><h2>作りたいものを、<br/>聞かせてください。</h2><p className="contact-form-lead">短いひと言からで大丈夫です。<br/>予算や時期が未定でも、ご相談いただけます。</p></div><ContactBrief/><div className="contact-foot"><p>課題の整理から、最初の一歩を一緒に考えます。</p><p>初回相談無料 / 全国オンライン対応 / 原則48時間以内に返信</p></div></div></section></main>}
