const groups=[
 {id:'developed-projects',title:'自社開発のプロダクト',description:'企画から開発・公開・改善まで、自分たちで取り組んでいます。',items:[
  {id:'aiplun-app',name:'アイプラ',type:'AIデートプランアプリ',image:'/aiplun-screen.webp',alt:'アイプラのApp Store掲載画像。AIがデートプランを提案するアプリ',width:600,height:1300,style:'app',description:'エリア・雰囲気・予算に合わせて、AIがデートプランを提案。UI設計からストア公開、課金導入、運用改善まで対応。',tags:['iOSアプリ','AIプラン提案','企画・開発・運用'],href:'https://apps.apple.com/jp/app/id6758015455',action:'App Storeで見る',external:true},
  {id:'quest-ai',name:'クエストAI',type:'LINE連携・セミナー運営CRM',image:'/quest-ai-dashboard-original.jpg',alt:'クエストAIの管理画面。顧客管理、セミナー作成、LINE配信のダッシュボード',width:2048,height:1186,style:'system',description:'申込・LINE案内・QR受付・アンケートをひとつの仕組みに。開催前から開催後のフォローまで、運営の手間を減らします。',tags:['顧客管理','LINE配信','QR受付'],href:'/works/quest-ai',action:'画面と機能を見る'},
 ]},
 {id:'web-projects',title:'Webサイトの制作サンプル',description:'ホテル・カフェを題材に、デザインと使い方のイメージをご紹介します。',items:[
  {id:'suiren',name:'SUIREN',type:'ホテル・旅館のWebサイト',image:'/suiren-preview.webp',alt:'SUIRENのトップ画面。海を望むホテルの写真と海と余白との見出し',width:1200,height:750,style:'hotel',description:'写真と余白でホテルの世界観を伝えるサイト。客室・料理の紹介から、宿泊を検討する方への案内につなげます。',tags:['写真を活かす設計','客室・料理紹介','アニメーション'],href:'https://suiren-ocean-retreat.roy-0817-soccer.chatgpt.site',action:'デモサイトを見る',external:true,note:'架空のホテルを題材にした制作サンプルです。'},
  {id:'komorebi',name:'KOMOREBI',type:'カフェ・店舗のWebサイト',image:'/komorebi-preview.webp',alt:'KOMOREBIのトップ画面。木漏れ日が差し込むカフェの写真を使ったデザイン',width:1200,height:750,style:'cafe',description:'温かみのある色と写真で、カフェの雰囲気を表現。メニュー・店内紹介・アクセスをまとめ、来店のきっかけをつくります。',tags:['店舗の世界観','メニュー紹介','来店案内'],href:'https://komorebi-coffee-bake.roy-0817-soccer.chatgpt.site',action:'デモサイトを見る',external:true,note:'架空のカフェを題材にした制作サンプルです。'},
 ]},
];
export default function WorksShowcase(){return <>
 <div className="section-heading works-heading"><h2>開発実績と、Web制作例。</h2><p>自社開発の2つのプロダクトと、<br/>Webサイトの制作サンプルをご覧いただけます。</p></div>
 <nav className="work-group-nav" aria-label="実績の種類から選ぶ"><a href="#developed-projects">自社開発 <span>2件 ↓</span></a><a href="#web-projects">Web制作サンプル <span>2件 ↓</span></a></nav>
 {groups.map((group,index)=><section className="work-group" id={group.id} key={group.id} aria-labelledby={group.id+'-title'}><div className="work-group-heading"><div><p className="eyebrow">0{index+1} / {index===0?'OUR PRODUCTS':'WEB DESIGN'}</p><h3 id={group.id+'-title'}>{group.title}</h3></div><p>{group.description}</p></div><div className="work-gallery" id={index===0?'works-track':undefined}>{group.items.map(item=><article className={'project-card project-'+item.style} id={item.id} key={item.id}>
 <a className="project-media" href={item.id==='quest-ai'?'/quest-ai-dashboard-original.jpg':item.href} target="_blank" rel="noopener noreferrer" aria-label={item.name+(item.id==='quest-ai'?'の管理画面を拡大する':'を開く')+'（新しいタブ）'}><img src={item.image} alt={item.alt} width={item.width} height={item.height} loading="lazy" decoding="async"/><span className="project-media-label">{item.id==='quest-ai'?'実際の管理画面を拡大':item.id==='aiplun-app'?'公開中のiOSアプリ':'デモサイトを開く'} <span aria-hidden="true">↗</span></span></a>
 <div className="project-copy"><div className="project-meta"><span className={'project-badge'+(index===1?' is-sample':'')}>{index===0?'自社開発':'制作サンプル'}</span><span>{item.type}</span></div><h4>{item.name}</h4><p className="project-description">{item.description}</p><ul className="project-tags">{item.tags.map(tag=><li key={tag}>{tag}</li>)}</ul><div className="project-actions"><a className="project-primary" href={item.href} target={item.external?'_blank':undefined} rel={item.external?'noopener noreferrer':undefined}>{item.action}<span aria-hidden="true">{item.external?'↗':'→'}</span></a><a className="project-consult" href="#contact">似たものを相談する <span aria-hidden="true">→</span></a></div>{item.note&&<p className="project-note">※ {item.note}実在施設の受託実績ではありません。</p>}</div>
 </article>)}</div></section>)}
 </>}
