'use client';
import {useState} from 'react';
import {calculateSavings,defaultSavings,savingsFields,normalizeSavings,formatNumber} from '../../lib/savings.mjs';
import DiagnosisLink from './DiagnosisLink';
export default function SavingsSimulator() {
 const [values,setValues]=useState(defaultSavings);
 const [period,setPeriod]=useState('year');
 const invalid=savingsFields.some(f=>values[f.key]===''||!Number.isFinite(Number(values[f.key]))||Number(values[f.key])<f.min||Number(values[f.key])>f.max);
 const result=calculateSavings(values);
 const normalized=normalizeSavings(values);
 const amount=period==='year'?result.annualSavings:result.monthlySavings;
 const update=(key,value)=>setValues(current=>({...current,[key]:value}));
 return <section className="ai-calculator-section section wrap" id="ai-simulator" aria-labelledby="simulator-title"><div className="ai-section-heading" data-reveal><p className="eyebrow">YOUR BUSINESS, IN NUMBERS.</p><h2 id="simulator-title">あなたの会社では、<br/>いくら削減できる？</h2><p>毎日の定型業務を、時間とコストで見える化。<br/>自社の条件に合わせて、業務改善の可能性を試算してください。</p></div><div className="ai-calculator"><div className="ai-controls"><div className="ai-controls-heading"><h3>現在の業務を教えてください</h3><span>01 — INPUT</span></div>{savingsFields.map(field=><div className="ai-control" key={field.key}><div className="ai-control-top"><label htmlFor={'savings-'+field.key}>{field.label}</label><div className="ai-number-input"><input id={'savings-'+field.key} type="number" inputMode={field.step<1?'decimal':'numeric'} min={field.min} max={field.max} step={field.step} value={values[field.key]} onChange={e=>update(field.key,e.target.value)} onBlur={()=>update(field.key,normalized[field.key])} aria-describedby={'savings-'+field.key+'-limits'}/><span>{field.unit}</span></div></div><input className="ai-range" type="range" min={field.min} max={field.max} step={field.step} value={normalized[field.key]} aria-label={field.label+'（スライダー）'} aria-valuetext={formatNumber(normalized[field.key])+field.unit} onChange={e=>update(field.key,Number(e.target.value))} style={{'--range-fill':((normalized[field.key]-field.min)/(field.max-field.min)*100)+'%'}}/><div className="ai-range-limits" id={'savings-'+field.key+'-limits'}><span>{formatNumber(field.min)}{field.unit}</span><span>{formatNumber(field.max)}{field.unit}</span></div></div>)}<p className="ai-input-note">削減率はご自身の想定値です。実際に削減できる割合は業務を確認して検証します。</p></div>
 <div className="ai-result"><div className="ai-result-top"><span>02 — ESTIMATE</span><div className="ai-period" role="group" aria-label="試算期間"><button type="button" aria-pressed={period==='month'} onClick={()=>setPeriod('month')}>月間</button><button type="button" aria-pressed={period==='year'} onClick={()=>setPeriod('year')}>年間</button></div></div><div className="ai-result-main" aria-live="polite" aria-atomic="true">{invalid?<p className="ai-result-invalid">各項目を表示範囲内で入力してください。</p>:<><p>{period==='year'?'年間':'月間'}の業務時間相当</p><div className="ai-result-amount" key={period}><span>約</span><strong>{formatNumber(amount/10000)}</strong><span>万円</span></div><p className="ai-result-possibility">削減できる可能性</p><div className="ai-time-result">月 <strong>{formatNumber(result.savedHours)}時間</strong> を、本来の仕事へ。</div></>}</div><div className="ai-cost-comparison"><div><span>現在の業務コスト / 月</span><strong>{invalid?'—':formatNumber(result.monthlyCost)}円</strong></div><div className="ai-cost-bar" aria-hidden="true"><span style={{width:normalized.rate+'%'}}/></div><div><span>削減想定 {normalized.rate}% / 月</span><strong>{invalid?'—':formatNumber(result.monthlySavings)}円</strong></div><div><span>残る業務時間の換算額 / 月</span><strong>{invalid?'—':formatNumber(result.remainingCost)}円</strong></div></div><p className="ai-result-formula">{normalized.people}人 × {normalized.hours}時間 × {formatNumber(normalized.hourlyCost)}円 × {normalized.days}日<br/>× 想定削減率 {normalized.rate}%{period==='year'?' × 12か月':''}</p><p className="ai-result-note">モデルケースによる試算です。実際の効果は業務内容・利用状況によって異なります。人件費の支出削減や利益増加を保証するものではありません。導入費用・運用費用は含みません。</p></div></div>
 <div className="ai-diagnosis" data-reveal><div><p className="eyebrow">30分の無料ヒアリング</p><h3>あなたの会社でAI化できる業務を無料診断</h3><p>30分のヒアリングで、AI・システム化できる業務と、<br className="ai-desktop-break"/>削減できる時間・コストの目安を整理します。</p></div><DiagnosisLink/></div></section>;
}
