// Only publish measured results with an attributable source and measurement period.
// Future results: evidence = {kind:'measured', sourceUrl, period, scope}; keep separate from estimates.
export const industryCases = [
 {id:'events',name:'セミナー・イベント運営',icon:'calendar',headline:'運営の手間を減らし、参加者との関係づくりへ。',
  problems:['申込確認と名簿作成が毎回手作業','LINE・メールのリマインドを手動送信','当日受付とアンケート集計に人手が必要','イベント後の営業フォローが遅れる'],
  before:['申込を確認','名簿に転記','リマインド送信','当日受付','アンケート回収','手作業で集計','営業フォロー'],
  after:[['申込情報を自動管理','一元管理'],['LINE・メール送信','自動通知'],['QRコードで受付','自動化'],['アンケートを整理','AI補助'],['見込み顧客を整理','AI補助'],['営業フォローへ','人が判断']],
  human:'見込み顧客の判断と個別提案は担当者が確認。運営からフォローまでをつなぐ導入イメージです。',
  evidence:{kind:'model',beforeHours:40,afterHours:10,savedHours:30,hourlyCost:2000,formula:'月40時間の事務作業 → 月10時間を想定'},
  related:{href:'/services/seminar-automation',label:'セミナー運営の自動化・LINE連携を詳しく見る'},
 },
 {id:'care',name:'介護・福祉',icon:'file',headline:'記録に追われる時間を、利用者と向き合う時間へ。',
  problems:['記録作成に時間がかかる','紙・Excel・LINEに情報が分散','同じ質問への回答が何度も発生','スタッフ間の共有と報告資料の作成が負担'],
  before:['記録を手入力','情報を探し回る','同じ質問に回答','スタッフへ個別共有','報告資料を作成'],
  after:[['音声・メモから記録の下書き','AI補助'],['利用者情報をまとめる','一元管理'],['社内資料をAI検索','検索'],['社内FAQの一次対応','自動化'],['報告資料の下書き','AI補助']],
  human:'記録・報告は職員が確認して確定。個人情報の扱いと閲覧権限を整理したうえで設計します。',
  evidence:{kind:'model',savedHours:33,hourlyCost:2000,formula:'1日1.5時間 × 22営業日 × 時給2,000円'},
 },
 {id:'stores',name:'飲食店・店舗',icon:'store',headline:'電話と投稿に追われず、目の前のお客様に集中。',
  problems:['予約問い合わせや電話で接客が中断','Instagram・SNSの文章作成に時間がかかる','口コミへの返信が後回し','営業時間・メニューについて同じ質問が届く'],
  before:['予約・電話に対応','よくある質問に回答','口コミ返信を作成','SNS投稿文を作成','顧客情報を整理','再来店の案内'],
  after:[['予約問い合わせの一次対応','自動化'],['営業時間・メニューのFAQ','自動対応'],['口コミ返信案を生成','AI補助'],['SNS投稿案を作成','AI補助'],['顧客情報をまとめる','一元管理'],['再来店フォロー','自動通知']],
  human:'予約の確定は予約システムの空き状況と連携。口コミ返信や投稿の内容はスタッフが確認して公開します。',
  evidence:{kind:'model',savedHours:26,hourlyCost:1500,formula:'1日1時間 × 月26日 × 時給1,500円'},
 },
 {id:'sales',name:'営業・人材・コンサル',icon:'briefcase',headline:'営業マンの仕事をなくすAIではなく、営業マンが「営業」に集中するためのAI。',
  problems:['営業先の企業HPを一社ずつ調査','営業メールを毎回ゼロから作成','商談後の議事録とCRM入力に時間がかかる','追客や次のアクションが漏れる'],
  before:['企業情報を収集','HPを読んで調査','営業メールを作成','議事録を作成','CRMへ転記','追客を個別管理'],
  after:[['企業情報を収集','連携'],['企業調査を要約','AI補助'],['営業文の下書き','AI補助'],['商談議事録を整理','AI補助'],['CRMへ入力','自動化'],['フォロータスク作成','自動通知']],
  human:'調査の出典や提案内容は担当者が確認。送信と商談の判断は人が担い、準備と入力を効率化します。',
  evidence:{kind:'model',savedHours:null,formula:'人数・業務時間に応じて個別に試算'},
 },
];
export const servicePaths=[
 ['AI業務自動化','問い合わせ・検索・定型作業を効率化','/services/ai-automation'],
 ['業務システム開発','散らばった情報と仕事の流れを一元化','/services/business-systems'],
 ['Web制作','問い合わせ・予約につながる窓口をつくる','/services/web-production'],
 ['アプリ / MVP開発','新しい仕組みを小さく試して育てる','/services/app-development'],
];
